version: '3.8'

services:
  test_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./init_test_db.sql:/docker-entrypoint-initdb.d/init.sql

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DATABASE_URL=${TEST_DATABASE_URL}
      - TELEGRAM_TOKEN=${TEST_TELEGRAM_TOKEN}
    depends_on:
      - test_db
    volumes:
      - ./test-results:/app/test-results 